/******************************************************************************
filename    GoCommandHandler.c
author      Matthew Picioccio
DP email    mattpic@digipen.edu
course      GAM100 ** Do not use this code in your team project

Brief Description:
This file defines functions that handle the "go" user command, which moves
the user from one room to another using defined exits.

******************************************************************************/
#include "stdafx.h" /* NULL, printf */
#include "GoCommandHandler.h" /* Function declarations */
#include "CommandData.h" /* struct CommandData */
#include "GameState.h" /* struct GameState */
#include "WorldData.h" /* WorldData_GetRoom */
#include "Room.h" /* Room_GetNextRoomIndex, Room_Print, INVALID_DIRECTION_ID */

#define MAPHEIGHT 27 /* Map Height */
#define MAPWIDTH 61 /*  Map Width */

#define SPACE ' '  /* Space */
#define VWALL '|'  /* Verticle wall */
#define HWALL '-'  /* Horizontal wall */
#define CORNR '+'  /* Corner */
#define DOOR_ 'I'  /* Door */
#define BSLSH '\\' /* Back slash */
#define FSLSH '/'  /* Foward slash */
#define UDSCR '_'  /* Underscore */
#define ORPHN 'O'  /* NPC */
#define SHUNK 'X'  /* Player */

/* MAP: (Excluding the wall on the right)
        +------------------+                                |
        |                  |                                |
        |                  |                                |
        |                  |                                |
        |                  |                                |
        |                  |                                |
        |                  |                                |
        |                  |                                |
        +----+----+--I-----+-+                              |
             |    I          |                              |
        +----|    |          |                              |
        |    I    |          |                              |
        |    |    |--I--+----+     _____________________    |
        +----|    |     |         /                    ||   |
             |    |     |        /                     \/   |
    +-----+  |    |     |       /     +---------------+-I--+|
    |     |  |    |--I--+      /      |               |    ||
    +--I--+--|    |  ||       /       |               I    ||
    |        I    |   \______/        |               |----+|
+---+--I-+---|    |                   |               |     |
|        |   |    |                   |               |     |
|        |   +-I--+-----+             +---------------+     |
|        |   |          |                                   |
+--------+   |          |                                   |
             |          |                                   |
             |          |                                   |
             +----------+                                   |
*/
/* Handles the "go" command, which moves the user to another room */
void HandleGoCommand(CommandData *command, GameState *gameState, WorldData *worldData)
{
	Room* currentRoom; /* the room we are currently in */
	int nextRoomIndex; /* the index of hte next room */
	/* safety check on the parameters */
	if ((command == NULL) || (command->noun == NULL) || (gameState == NULL) || (worldData == NULL)) 
	{
		return; /* take no action if the parameters are invalid */
	}

	/* get the current room, based on the user state */
	currentRoom = WorldData_GetRoom(worldData, gameState->currentRoomIndex);

	/* get the next room index, based on the noun used with "go" */
	if (Room_GetNextRoomIndex(currentRoom, command->noun, &nextRoomIndex) == false)
	{
		/* there is no exit in that direction, so let the user know and take no other action */
		printf("You cannot move %s.\n", command->noun);
		return;
	}

	/* update the game state to move to the new room */
	gameState->currentRoomIndex = nextRoomIndex;

	/* output the successful action */
	printf("You move %s.\n\n", command->noun);

	/* Print map */
	printMap(gameState);

	/* get the new room */
	currentRoom = WorldData_GetRoom(worldData, gameState->currentRoomIndex);

	/* print the description of the new room */
	Room_Print(currentRoom);
}

/* Prints out the map with all moving pieces shown on it */
void printMap(GameState* gameState)
{
	int map[MAPHEIGHT][MAPWIDTH] = 
	{
		{SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, CORNR, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, CORNR, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE}, 
		{SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE}, 
		{SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE}, 
		{SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE}, 
		{SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE}, 
		{SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE}, 
		{SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE}, 
		{SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE}, 
		{SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, CORNR, HWALL, HWALL, HWALL, HWALL, CORNR, HWALL, HWALL, HWALL, HWALL, CORNR, HWALL, HWALL, DOOR_, HWALL, HWALL, HWALL, HWALL, HWALL, CORNR, HWALL, CORNR, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE}, 
		{SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, DOOR_, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE}, 
		{SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, CORNR, HWALL, HWALL, HWALL, HWALL, VWALL, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE}, 
		{SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, DOOR_, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE}, 
		{SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, VWALL, HWALL, HWALL, DOOR_, HWALL, HWALL, CORNR, HWALL, HWALL, HWALL, HWALL, CORNR, SPACE, SPACE, SPACE, SPACE, SPACE, UDSCR, UDSCR, UDSCR, UDSCR, UDSCR, UDSCR, UDSCR, UDSCR, UDSCR, UDSCR, UDSCR, UDSCR, UDSCR, UDSCR, UDSCR, UDSCR, UDSCR, UDSCR, UDSCR, UDSCR, UDSCR, SPACE, SPACE, SPACE, SPACE, SPACE}, 
		{SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, CORNR, HWALL, HWALL, HWALL, HWALL, VWALL, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, FSLSH, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, VWALL, SPACE, SPACE, SPACE, SPACE}, 
		{SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, FSLSH, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, BSLSH, FSLSH, SPACE, SPACE, SPACE, SPACE}, 
		{SPACE, SPACE, SPACE, SPACE, CORNR, HWALL, HWALL, HWALL, HWALL, HWALL, CORNR, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, FSLSH, SPACE, SPACE, SPACE, SPACE, SPACE, CORNR, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, CORNR, HWALL, DOOR_, HWALL, HWALL, CORNR, SPACE}, 
		{SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, VWALL, HWALL, HWALL, DOOR_, HWALL, HWALL, CORNR, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, FSLSH, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE}, 
		{SPACE, SPACE, SPACE, SPACE, CORNR, HWALL, HWALL, DOOR_, HWALL, HWALL, CORNR, HWALL, HWALL, VWALL, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, VWALL, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, FSLSH, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, DOOR_, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE}, 
		{SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, DOOR_, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, BSLSH, UDSCR, UDSCR, UDSCR, UDSCR, UDSCR, UDSCR, FSLSH, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, HWALL, HWALL, HWALL, HWALL, CORNR, SPACE}, 
		{CORNR, HWALL, HWALL, HWALL, CORNR, HWALL, HWALL, DOOR_, HWALL, CORNR, HWALL, HWALL, HWALL, VWALL, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE}, 
		{VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE}, 
		{VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, CORNR, HWALL, DOOR_, HWALL, HWALL, CORNR, HWALL, HWALL, HWALL, HWALL, HWALL, CORNR, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, CORNR, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, CORNR, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE}, 
		{VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE}, 
		{CORNR, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, CORNR, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE}, 
		{SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE}, 
		{SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, VWALL, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE}, 
		{SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, CORNR, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, HWALL, CORNR, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE}
	};

		int roomPosition[11][2] = {{6, 16}, {8, 17}, {10, 19}, {6, 22}, {19, 25}, {22, 15}, {11, 24}, {18,5}, {16, 16}, {57, 18}, {52,18}};
		/* counter variables */
		int X, Y = 0;
		int * curRoomPosition= roomPosition[gameState->currentRoomIndex];
		/* loop through each array in the map */
		for (Y = 0; Y < MAPHEIGHT; ++Y)
		{
			/* loop through all characters in the array  */
			for (X = 0; X < MAPWIDTH; ++X)
			{
				if (curRoomPosition[0] == X && curRoomPosition[1] == Y)
				{
					printf("X");
				}
				else
				{
					printf("%c", map[Y][X]);
				}
			}
			/* each new map line add a newline */
			putchar('\n');
	}
}