/******************************************************************************
filename    targetver.h
author      Matthew Picioccio (autogenerated)
DP email    mattpic@digipen.edu
course      GAM100 ** Do not use this code in your team project

Brief Description:
Including SDKDDKVer.h defines the highest available Windows platform.

If you wish to build your application for a previous Windows platform, include WinSDKVer.h and
set the _WIN32_WINNT macro to the platform you wish to support before including SDKDDKVer.h.

******************************************************************************/
#pragma once

#include <SDKDDKVer.h> /* required by Windows */

/* NOTE: there must be at least one empty line after the #include, or the compiler gets confused */